services:
  mysql:
    image: mysql:8.0
    container_name: mysql_host
    ports:
      - "3307:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci